- name: Listar contenido de un directorio
  hosts: all
  become: yes
  tasks:

    - name: Listar un archivo o directorio con 'ls'
      command: ls /tmp
      register: ls_output

    - name: Mostrar cada línea de salida del ls
      debug:
        msg: "{{ item }}"
      loop: "{{ ls_output.stdout_lines }}"

