---
- name: Listar contenido de un directorio
  hosts: localhost
  tasks:
    - name: Listar un archivo o directorio con 'ls'
      command: ls /tmp
      register: resultado_ls

    - name: Mostrar el resultado del comando ls
      debug:
        msg: "{{ resultado_ls.stdout }}"

